config/routes.rb
AskServer::Application.routes.draw do
  resources :commands do
    collection do
      get 'query'
    end
  end

end

app/models/command.rb
class Command < ActiveRecord::Base
  attr_accessible :command, :description, :private
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/commands_controller.rb
class CommandsController < ApplicationController
  protect_from_forgery only: nil

  # GET /commands
  # GET /commands.json
  def index
    @commands = Command.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @commands }
    end
  end

  def query
    @commands = Command.where('command like ?', "%#{params[:q]}%")
    respond_to do |format|
      format.html { render :index }
      format.json { render json: @commands }
    end
  end

  # GET /commands/1
  # GET /commands/1.json
  def show
    @command = Command.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @command }
    end
  end

  # GET /commands/new
  # GET /commands/new.json
  def new
    @command = Command.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @command }
    end
  end

  # GET /commands/1/edit
  def edit
    @command = Command.find(params[:id])
  end

  # POST /commands
  # POST /commands.json
  def create
    @command = Command.new(params[:command])

    respond_to do |format|
      if @command.save
        format.html { redirect_to @command, notice: 'Command was successfully created.' }
        format.json { render json: @command, status: :created, location: @command }
      else
        format.html { render action: "new" }
        format.json { render json: @command.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /commands/1
  # PUT /commands/1.json
  def update
    @command = Command.find(params[:id])

    respond_to do |format|
      if @command.update_attributes(params[:command])
        format.html { redirect_to @command, notice: 'Command was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @command.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /commands/1
  # DELETE /commands/1.json
  def destroy
    @command = Command.find(params[:id])
    @command.destroy

    respond_to do |format|
      format.html { redirect_to commands_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/commands_helper.rb
module CommandsHelper
end

app/views/commands/_form.html.haml
= form_for @command do |f|
  - if @command.errors.any?
    #error_explanation
      %h2= "#{pluralize(@command.errors.count, "error")} prohibited this command from being saved:"
      %ul
        - @command.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :command
    = f.text_field :command
  .field
    = f.label :description
    = f.text_field :description
  .field
    = f.label :private
    = f.check_box :private
  .actions
    = f.submit 'Save'

app/views/commands/edit.html.haml
%h1 Editing command

= render 'form'

= link_to 'Show', @command
\|
= link_to 'Back', commands_path

app/views/commands/index.html.haml
%h1 Listing commands

%table
  %tr
    %th Command
    %th Description
    %th Private
    %th
    %th
    %th

  - @commands.each do |command|
    %tr
      %td= command.command
      %td= command.description
      %td= command.private
      %td= link_to 'Show', command
      %td= link_to 'Edit', edit_command_path(command)
      %td= link_to 'Destroy', command, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Command', new_command_path

app/views/commands/new.html.haml
%h1 New command

= render 'form'

= link_to 'Back', commands_path

app/views/commands/show.html.haml
%p#notice= notice

%p
  %b Command:
  = @command.command
%p
  %b Description:
  = @command.description
%p
  %b Private:
  = @command.private

= link_to 'Edit', edit_command_path(@command)
\|
= link_to 'Back', commands_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AskServer</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>